name: Deploy to Neocities

on:
  push:
    branches:
      - main  # Change this if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Neocities
        uses: neocities/deploy@v1
        with:
          site: ${{ secrets.NEOCITIES_SITE }}  # Your Neocities subdomain
          api_key: ${{ secrets.NEOCITIES_API_KEY }}  # Your Neocities API key
          path: docs  # Path to your website files
          cleanup: true
